### PR TITLE
Add gui for Comcast DSCP fix.

### PR DESCRIPTION
**Pull request by lancethepants**
I placed the checkbox under Advanced -> Firewall -> Firewall. Seemed the appropriate place, but you can let me know if you want it elsewhere. Enabled by default seemed to be the consensus of the code and comments in the forum.

### CODE REVIEW

**Comment by Victek** [comment]
What do you think if we avoid unnecessary testing same condition? like:

if (nvram_match("DSCP_fix_enable","1")) {
#ifdef LINUX26
    modprobe("xt_DSCP");
#else
    modprobe("ipt_DSCP");
#endif
    ipt_write("-I PREROUTING -i %s -j DSCP --set-dscp 0\n", wanface);
}

(then using this reverse condition allows you to use corner cases easier, not?... could you test?)

Coment by @roadkill
About the toggle function, it should work cause dscp is a register in the post routing chain used like this and the firewall restart will trigger a iptables rules flush ...

Thanks

**Comment by lancethepants** [comment]
I'm thinking that you are right.  It looked funny to me before, but now after looking at it again, I think it will work fine as you suggest.  I'll test again and will report back

**Comment by lancethepants** [comment]
I've finally  got to updating and testing the code. It also works just fine with the new edits.

I really how like how git pull request works. All I have to do is push another commit to the same branch, and it shows up here!

**Comment by lancethepants** [comment]
Just learned how to squash commits and rebase my branch (working branch of course), so they will be just one commit for merging. See if you find this acceptable anyway.

**Pull request merged**
